namespace TestProject.Business
{
    /*  A MetadataStorage is responsible for storing and managing metadata of items that can be found using the search engine. 
     *  It provides methods to get, delete, update, copy, and save items based on their unique identifiers. The interface ensures 
     *  that any implementation will adhere to these operations, allowing for consistent management of metadata across different 
     *  storage solutions.
     *  
     *  The metadata storeage instance is responsible for assigning the Id value to the new item when saving it. The Id value is 
     *  generated by the storage and is not provided by the caller. This ensures that each item has a unique identifier that can 
     *  be used for retrieval, deletion, and other operations.
    */

    public interface IMetadataStorage<T> where T : IFindable
    {
        /// <summary>
        /// finds a metadata item by its unique identifier. The method returns a Task that, when completed, will provide the metadata item associated with the given id.
        /// </summary>
        /// <param name="id">The unique identifier of the entity to delete.</param>
        /// <returns></returns>
        Task<T> Get(int id);


        /// <summary>
        /// Deletes the entity with the specified identifier.   
        /// </summary>
        /// <param name="id">The unique identifier of the entity to delete.</param>
        /// <returns>A task that represents the asynchronous delete operation.</returns>
        Task Delete(int id);


        /// <summary>
        /// Updates the metadata entity, specified by the item id, with the values of the item.    
        /// </summary>
        /// <param name="id">The unique identifier of the entity to update.</param>
        /// <param name="parentId">The unique identifier of the parent entity to associate with the updated entity.</param>
        /// <returns>A task that represents the asynchronous operation.</returns>
        Task Update(T item);


        /// <summary>
        /// Adds a new item to the collection.
        /// </summary>
        /// <param name="newItem">The item to add to the collection. Cannot be <see langword="null"/>.</param>
        /// <returns>A task that represents the asynchronous operation.</returns>
        Task Add(T newItem);


        /// <summary>
        /// Generates and returns the next unique identifier.
        /// </summary>
        /// <returns>The next unique identifier as an integer.</returns>
        int GetNextId();


        /// <summary>
        /// Retrieves all items currently held in the metadata storage.
        /// </summary>
        /// <returns>A task that represents the asynchronous operation. The task result contains all stored items.</returns>
        Task<IEnumerable<T>> GetAll();


        /// <summary>
        /// Loads data from the specified file path asynchronously and populates the metadata storage with the loaded data. 
        /// </summary>
        /// <remarks>This method reads the contents of the file specified by <paramref name="path"/> and
        /// processes it asynchronously. Ensure the file exists and the application has the necessary permissions to
        /// access it.</remarks>
        /// <param name="path">The path to the file to be loaded. The path must not be null or empty.</param>
        /// <returns>A task that represents the asynchronous load operation.</returns>
        Task Load(string path);


        /// <summary>
        /// Saves the current metadata to the specified file path.
        /// </summary>
        /// <param name="path">The file path where the data will be saved. Must be a valid, writable path.</param>
        /// <returns>A task that represents the asynchronous save operation.</returns>
        Task Save(string path);
    }

}
